
/* What is DOM?
        -Document Object Model
        -Tree of Elements (Nodes) generated by Browser
        - JavaScript can manipulate DOM



    Tree of Nodes:
                                                Document
                                                    |
                                                    |
                                            Root Element: <html>
                                                     |
                                                     |
            Element: <head>  -------------------------------------------------  Element: <body>
                |                                                                   |
                |                                                                   |
    Element: Title                           Attribute: "href"   ------------   Element: <a>  ------------    Element: <h1>
            |                                                                       |                              |
            |                                                                       |                              |
    Text: "My Title"                                                            Text: "My link"               Text: "My head"
          

*/